### ISSUE TITLE
TypeError: set([]) is not JSON serializable

### ISSUE THREAD

**Issue by NickWoodhams** [jpvanhal/flask-split#3]
Hey there, are you interested in teaming up on updating the library? I see you haven't made any updates in a while and there appear to be a few things not working.

Getting this error when trying to track the conversion in the template.

{{ finished('get_started_top_btn_text') }}

**Comment by jpvanhal** [comment]
This has been fixed in version 0.3.0. Thanks for reporting!

**Comment by NickWoodhams** [comment]
Awesome, I appreciate your contribution.
